name: Deploy to Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: ZeroTier Setup
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}

      - name: Ping Host
        shell: bash
        run: |
          count=10
          while ! ping -c 1 ${{ secrets.ZEROTIER_HOST_IP }}; do
            echo "waiting...."
            sleep 1
            let count=count-1
            if [ $count -le 0 ]; then
              echo "Ping failed after multiple attempts."
              exit 1
            fi
          done
          echo "ping success"

      - name: SSH to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ZEROTIER_HOST_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/nixie/WEB_REKAM_MEDIS/
            # Set remote URL with PAT
            git remote set-url origin https://github.com/Tech-Evolution-Nexus/WEB_REKAM_MEDIS.git
            # Optional: Set Git config if needed
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            # Pull the latest changes
            git pull https://${{ secrets.GH_PAT }}@github.com/Tech-Evolution-Nexus/WEB_REKAM_MEDIS.git
